### ISSUE TITLE
Comments on released sky130 RAW data

### ISSUE THREAD

**Issue by msaligane** [google/skywater-pdk-sky130-raw-data#10]
@akinakturk @mithro 

Thanks for releasing this data. 
I have shared @proppy 's notebook with @bmurmann who modified it a bit to plot some of the most useful curves for analog designers.
The new notebook is here (available to anyone):
https://colab.research.google.com/drive/1PggoBDvjzV8aN_CluYQCiRV9qptRjlDq?usp=sharing&#scrollTo=QuGRGGmTCJMi

Saved as a gist here: [https://gist.github.com/msaligane/a4fcb8fdce99fec1e9f6a1229f3306b0/](https://gist.github.com/msaligane/a4fcb8fdce99fec1e9f6a1229f3306b0/#file-sky130-gm-ipynb)

Please take a look at the visualizations and added comments. Please let us know what you think.

Thanks again!

**Comment by bmurmann** [comment]
Thanks, @msaligane! I am planning to look at the ID-VD curves more closely as well, but for now this should be good material for discussion.

**Comment by mithro** [comment]
@bmurmann - Any chance you could send a pull request to add this notebook into this repository?

**Comment by bmurmann** [comment]
@mithro will do.

**Comment by proppy** [comment]
Closed with #11 .
