### ISSUE TITLE
GDS of the test chip

### ISSUE THREAD

**Issue by danchitnis** [google/skywater-pdk-sky130-raw-data#16]
Hello, is the GDS of the test chip available or going to be available? Optical images on their own are not helpful in some scenarios. Thanks

**Comment by mithro** [comment]
@danchitnis - See the README files. The GDS and schematic of the existing proprietary test chip is not available (and unlikely to be published). @msaligane and NIST are working on a new replacement fully open source test chip which will have both GDS and schematic available.

**Comment by danchitnis** [comment]
That is fine, hopefully, should be able to do some guesswork using the optical images if they are high-res enough.

**Comment by mithro** [comment]
FYI - There are a few people working on getting SEM and other high quality imaging of the test tiles various layers at https://bit.ly/sky130-mpw1-testtile-notes

See also the pad documentation linked from https://github.com/google/skywater-pdk-sky130-raw-data/tree/main/docs/sky130-testtile
