### ISSUE TITLE
Add a notebook which displays the data in a nicer format

### ISSUE THREAD

**Issue by mithro** [google/skywater-pdk-sky130-raw-data#2]
It would be great to visualize the data in this repository using Python and Juypter notebooks.

**Comment by mithro** [comment]
I believe @proppy had something.

**Comment by proppy** [comment]
https://colab.research.google.com/gist/proppy/00b7a5e58314a9d387e8174581c77866/skywater-pdk-sky130-raw-data.ipynb

**Comment by mithro** [comment]
@proppy - Will you send a pull request with this notebook into this repository?
